wandb_version: 1

batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 200
clip_duration:
  desc: null
  value: 10
model:
  desc: null
  value: resnet-lstm
num_classes:
  desc: null
  value: 101
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1734321903
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.17.9
      6: 4.39.3
      8:
      - 4
      - 5
      13: darwin-arm64
